version: '3'

services:
  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: sqlite:///school.db
    ports:
      - "5000:5000"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: school_db
    ports:
      - "5432:5432"
